[package]
name = "rustatus"
version = "0.1.0"
authors = ["colton <cloftus@princeton.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
ipgeolocate = "0.3.5"
gag = "1.0.0"
dirs = "3.0.2"