# insert your modules in order
Modules:
   - Battery
   - Time
   - Network
   - Volume
   - Mouse Battery

# in milliseconds
Refresh_Rates:
   Battery: 10000
   Mouse Battery: 10000
   Network: 10000

Battery_Path : "/sys/class/power_supply/hidpp_battery_0/capacity_level"
