# insert your modules in order
Modules:
   - Battery
   - Time
   - Network

# in milliseconds
Refresh_rates:
   Battery: 10000

Battery_Path : "/sys/class/power_supply/hidpp_battery_0/capacity_level"
